function Questions()
	local rnd;

	-- Массив цитат на русском языке
	local msg_ru = {
		"Самое сложное - познать себя. Проще всего говорить плохо о других.",
		"Я ничему не могу научить. Я могу только заставить тебя думать.",
		"Худший бой это тот, который не ведется.",
		"Бедность приходит не из-за уменьшения богатства, а из-за умножения желаний.",
		"Не обижай других тем, что причиняет тебе боль.",
		"Ожидать многого от себя и не ожидать многого от других. Таким образом вы избавите себя от неприятностей.",
		"Наши самые глубокие убеждения, более несомненные, являются самыми подозрительными. Они составляют наш предел, наши границы, нашу тюрьму.",
		"У сердца есть причины, которые разум игнорирует.",
		"Тех, кто хорошо воспитывает детей, следует почитать больше, чем тех, кто их рожает. Первое дает им жизнь, второе – искусство жить хорошо.",
		"Мы редко думаем о том, что у нас есть, но всегда о том, чего нам не хватает.",
		"Я никогда не умру за свои убеждения, потому что я могу ошибаться.",
		"Наша жизнь всегда является результатом наших доминирующих мыслей.",
		"Часто можно узнать больше из неожиданных вопросов ребенка, чем из мужской речи.",
		"Каждый видит, кем ты являешься, но мало кто понимает, кем ты являешься.",
		"Важно не то, что с тобой происходит, а то, как ты реагируешь.",
		"Секрет счастья не в том, чтобы всегда делать то, что ты хочешь, а в том, чтобы всегда хотеть того, что ты делаешь.",
		"Терпение горько, но плод его сладок.",
		"Наша зависть всегда длится дольше, чем счастье того, кому мы завидуем.",
		"Жизнь без философствования – это, по сути, закрытие глаз, даже не попытавшись их открыть.",
		"Прошлое не имеет силы над настоящим моментом.",
		"Верьте, что ваша жизнь стоит того, и эта вера поможет создать этот факт.",
		"Мы видим вещи не такими, как они есть, а такими, какие мы есть.",
		"Чем больше я знаю людей, тем больше я люблю свою собаку.",
		"Думай как человек действия, действуй как человек мысли.",
		"Корни образования горькие, но плоды их сладки.",
		"Жизнь очень проста, но мы настаиваем на том, чтобы сделать ее сложной.",
		"Те, кто ведут и тянут мир, не машины, а идеи.",
		"Те, кто считают, что деньги делают все, в конечном итоге делают все за деньги.",
		"Мы более искренни, когда злимся, чем когда мы спокойны.",
		"Не парадоксальная мысль почти невыносима, мысль замкнута в себе, связна, которая не допускает парадокса.",
		"Есть родители, братья, дети, которые выходят каждый день на борьбу и гибнут в войнах по всему миру. Современная политика пытается сохранить это понятие «мы» и «они» со стеной между ними.",
		"Я понял, что надежда почти никогда не связана с разумом, она лишена здравого смысла, я считаю, что она рождается инстинктом.",
		"Время отдает все и забирает все. Все меняется, но ничего не погибает.",
		"Я не верю в смерть, потому что нет человека, который бы знал, что на самом деле это произошло.",
		"Странно, что они боятся смерти. Жизнь причиняет гораздо больше боли, чем смерть.",
		"Не позволяйте поведению других разрушить ваш внутренний мир.",
		"Когда очевидно, что цели не могут быть достигнуты, не корректируйте цели, а корректируйте действия.",
		"Живи так, как будто завтра умрешь. Учись так, как будто тебе суждено жить вечно.",
		"Есть только один способ избежать критики: ничего не делать, ничего не говорить и быть ничем.",
		"Чем больше человек размышляет о хороших мыслях, тем лучше будет его мир и мир в целом.",
		"Чтобы знать, что думают люди, обращайте внимание на то, что они делают, а не на то, что они говорят.",
		"Мы не описываем мир, который видим. Мы видим мир, который можем описать.",
		"Философия написана в той великой книге, которая всегда лежит перед нашими глазами - я имею в виду вселенную.",
		"Человек, совершивший ошибку и не исправивший ее, совершает еще одну ошибку.",
		"Если вы в депрессии, вы живете в прошлом. Если вы беспокоитесь, вы живете в будущем. Если вы пребываете в покое, вы живете настоящим.",
		"Лягушка в пруду мало знает об огромном океане.",
		"Человек любит только считать свои проблемы. Он не считает свое счастье.",
		"Мы те, кем притворяемся, поэтому мы должны быть осторожны с тем, кем притворяемся.",
		"Когда вы любите кого-то, вы любите человека таким, какой он есть, а не таким, каким вы хотели бы его видеть.",
		"Жизнь - это череда естественных и спонтанных изменений. Не сопротивляйтесь им это только порождает печаль. Пусть реальность будет реальностью.",
		"На мой взгляд мудрейший из всех - тот кто хотя бы раз в месяц может называть себя дураком - способность о которой сегодня не слышно.",
		"Вы должны позволить происходящему случиться. Все должно быть в твоих глазах равным - добро и зло красивое и уродливое глупое и мудрое.",
		"Когда возникает гнев подумай о последствиях.",
		--
		"Чем больше ты знаешь тем больше знаешь что не знаешь.",
		"Если они плюют тебе в спину значит ты их опередил.",
		"Разум существовал всегда но не всегда в разумной форме.",
		"Недостаточно иметь хороший ум главное - правильно им пользоваться.",
		"Неважно насколько медленно ты идешь пока ты не останавливаешься.",
		"Чтобы осознать кто ты есть нужно отказаться от того кем ты себя представляешь.",
		"Есть только один путь - тот которым идёшь ты.",
		"Не спеши к смерти навстречу она сама скоро придёт к тебе.",
		"Две вещи бесконечны: вселенная и человеческая глупость; и я не уверен насчёт вселенной.",
		"Разум существовал всегда, но не всегда в разумной форме.",
		"Чем больше вы знаете, тем больше вы знаете, что не знаете.",
		"Жизнь была полна ужасных несчастий, большинство из которых так и не произошло.",
		"Никогда не позволяйте своему чувству морали мешать вам поступать правильно.",
		"Алкоголь в малых дозах безвреден в любом количестве.",
		"Я не согласен с математикой. Считаю, что сумма нулей — страшная величина.",
		"Ничто так не способствует душевному спокойствию, как полное отсутствие собственного мнения.",
		"Нормальные люди — только те, которых вы мало знаете.",
		"Критиканы — это обычно те люди, которые были бы поэтами... если бы могли, но, потерпев неудачу, решили заняться критикой.",
		"Общение с людьми совращает к самоанализу.",
	}

	-- Массив цитат на английском языке
	local msg_en = {
		"The most difficult thing is to get to know yourself. The easiest thing to do is to speak ill of others.",
		"I can't teach you anything. I can only make you think.",
		"The worst fight is the one that isn't fought.",
		"Poverty does not come from a decrease in wealth but from an increase in desires.",
		"Don't hurt others with things that hurt you.",
		"Expect a lot from yourself and not expect a lot from others. In this way you will save yourself trouble.",
		"Our deepest beliefs the most unquestioned are the most suspicious. They are our limit our borders our prison.",
		"The heart has causes that the mind ignores.",
		"Those who raise children well should be honored more than those who give birth to them. The first gives them life the second the art of living well.",
		"We rarely think about what we have but always about what we lack.",
		"I will never die for my beliefs because I can be wrong.",
		"Our lives are always the result of our dominant thoughts.",
		"It is often possible to learn more from a child's unexpected questions than from a man's speech.",
		"Everyone sees who you are but few understand who you are.",
		"It's not what happens to you that matters it's how you react.",
		"The secret to happiness isn't always doing what you want but always wanting what you do.",
		"Patience is bitter but its fruit is sweet.",
		"Our envy always lasts longer than the happiness of the one we envy.",
		"A life without philosophizing is in fact closing one's eyes without ever trying to open them.",
		"The past has no power over the present moment.",
		"Believe that your life is worth it and that belief will help create that fact.",
		"We don't see things as they are but as we are.",
		"The more people I know the more I love my dog.",
		"Think like a man of action act like a man of thought.",
		"The roots of the formation are bitter but their fruits are sweet.",
		"Life is very simple but we insist on making it complicated.",
		"Those who lead and pull the world are not machines but ideas.",
		"Those who believe that money does everything end up doing everything for money.",
		"We are more sincere when we are angry than when we are calm.", 
		"Non-paradoxical thought is almost intolerable thought is self-contained coherent which does not admit of paradox.", 
		"There are parents brothers children who go out every day to fight and die in wars around the world. Modern politics tries to preserve this notion of <us> and <them> with a wall between them.", 
		"I realized that hope is almost never connected with reason it is devoid of common sense I believe that it is born of instinct.", 
		"Time gives everything and takes everything away. Everything changes but nothing dies.", 
		"I don't believe in death because there's no one who knows it actually happened.", 
		"It's strange that they're afraid of death. Life causes much more pain than death.", 
		"Don't let the behavior of others destroy your inner world.", 
		"When it is obvious that the goals cannot be achieved do not adjust the goals but adjust the actions.", 
		"Live like you're going to die tomorrow Learn as if you are destined to live forever.", 
		"There is only one way to avoid criticism: do nothing say nothing and be nothing.", 
		"The more a person thinks about good thoughts the better his world and the world as a whole will be.", 
		"To know what people are thinking pay attention to what they do not what they say.", 
		"We don't describe the world we see. We see a world that we can describe.", 
		"Philosophy is written in that great book that is always before our eyes and I mean the universe.", 
		"A person who makes a mistake and doesn't correct it makes another mistake.", 
		"If you're depressed you're living in the past. If you're worried you're living in the future. If you are at peace you are living in the present.", 
		"The frog in the pond doesn't know much about the vast ocean.", 
		"A person only likes to count his problems. He doesn't count his happiness.", 
		"We are who we pretend to be so we have to be careful who we pretend to be.", 
		"When you love someone you love them for who they are not as you would like them to be.", 
		"Life is a series of natural and spontaneous changes. Do not resist them it only breeds sorrow. Let reality be reality.", 
		"In my opinion the wisest of all is the one who can call himself a fool at least once a month an ability that is unheard of today.", 
		"You have to let it happen. Everything should be equal in your eyes - good and evil beautiful and ugly stupid and wise.", 
		"When anger arises think about the consequences.", 
		--
		"The more you know the more you know what you don't know.", 
		"If they spit in your back then you're ahead of them.", 
		"Mind has always existed but not always in a rational form.", 
		"It is not enough to have a good mind the main thing is to use it correctly.", 
		"It doesn't matter how slow you go as long as you don't stop.", 
		"In order to realize who you are you need to give up who you think you are.", 
		"There is only one way and that is the way you go.", 
		"Do not rush to meet death it will soon come to you.",
		"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
		"Reason has always existed, but not always in intelligent form.",
		"Life was full of terrible misfortunes, most of which never happened.",
		"Never let your sense of morality stop you from doing the right thing.",
		"Alcohol in small doses is harmless in any quantity.",
		"I don't agree with the math. I think that the sum of zeros is a terrible value.",
		"Nothing contributes to peace of mind more than a complete absence of your own opinion.",
		"Normal people are the only ones you don't know well.",
		"Critics are usually those people who would be poets... if they could, but, having failed, decided to take up criticism.",
		"Communication with people seduces you into introspection.",
	}

	if SOULFUL_CONFIG["language"] == "RU" then
		rnd = math.random(1,table.getn(msg_ru));
		return msg_ru[rnd];
	elseif SOULFUL_CONFIG["language"] == "EN" then
		rnd = math.random(1,table.getn(msg_en));
		return msg_en[rnd];
	end;
end;