function Questions()
	local rnd;
	local msg;
	if SOULFUL_CONFIG["language"] =="RU" then 
		rnd=math.random(1,61);
		if rnd==1 then msg={"Самое сложное - познать себя. Проще всего говорить плохо о других."} end;
		if rnd==2 then msg={"Я ничему не могу научить. Я могу только заставить тебя думать."} end;
		if rnd==3 then msg={"Худший бой это тот, который не ведется."} end;
		if rnd==4 then msg={"Бедность приходит не из-за уменьшения богатства, а из-за умножения желаний."} end;
		if rnd==5 then msg={"Не обижай других тем, что причиняет тебе боль."} end;
		if rnd==6 then msg={"Ожидать многого от себя и не ожидать многого от других. Таким образом вы избавите себя от неприятностей."} end;
		if rnd==7 then msg={"Наши самые глубокие убеждения, более несомненные, являются самыми подозрительными."," Они составляют наш предел, наши границы, нашу тюрьму."} end;
		if rnd==8 then msg={"У сердца есть причины, которые разум игнорирует."} end;
		if rnd==9 then msg={"Тех, кто хорошо воспитывает детей, следует почитать больше, чем тех, кто их рожает."," Первое дает им жизнь, второе – искусство жить хорошо."} end;
		if rnd==10 then msg={"Мы редко думаем о том, что у нас есть, но всегда о том, чего нам не хватает."} end;
		if rnd==11 then msg={"Я никогда не умру за свои убеждения, потому что я могу ошибаться."} end;
		if rnd==12 then msg={"Наша жизнь всегда является результатом наших доминирующих мыслей."} end;
		if rnd==13 then msg={"Часто можно узнать больше из неожиданных вопросов ребенка, чем из мужской речи."} end;
		if rnd==14 then msg={"Каждый видит, кем ты являешься, но мало кто понимает, кем ты являешься."} end;
		if rnd==15 then msg={"Важно не то, что с тобой происходит, а то, как ты реагируешь."} end;
		if rnd==16 then msg={"Секрет счастья не в том, чтобы всегда делать то, что ты хочешь, а в том, чтобы всегда хотеть того, что ты делаешь."} end;
		if rnd==17 then msg={"Терпение горько, но плод его сладок."} end;
		if rnd==18 then msg={"Наша зависть всегда длится дольше, чем счастье того, кому мы завидуем."} end;
		if rnd==19 then msg={"Жизнь без философствования – это, по сути, закрытие глаз, даже не попытавшись их открыть."} end;
		if rnd==20 then msg={"Прошлое не имеет силы над настоящим моментом."} end;
		if rnd==21 then msg={"Верьте, что ваша жизнь стоит того, и эта вера поможет создать этот факт."} end;
		if rnd==22 then msg={"Мы видим вещи не такими, как они есть, а такими, какие мы есть."} end;
		if rnd==23 then msg={"Чем больше я знаю людей, тем больше я люблю свою собаку."} end;
		if rnd==24 then msg={"Думай как человек действия, действуй как человек мысли."} end;
		if rnd==25 then msg={"Корни образования горькие, но плоды их сладки."} end;
		if rnd==26 then msg={"Жизнь очень проста, но мы настаиваем на том, чтобы сделать ее сложной."} end;
		if rnd==27 then msg={"Те, кто ведут и тянут мир, не машины, а идеи."} end;
		if rnd==28 then msg={"Те, кто считают, что деньги делают все, в конечном итоге делают все за деньги."} end;
		if rnd==29 then msg={"Мы более искренни, когда злимся, чем когда мы спокойны."} end;
		if rnd==30 then msg={"Не парадоксальная мысль почти невыносима, мысль замкнута в себе, связна, которая не допускает парадокса."} end;
		if rnd==31 then msg={"Есть родители, братья, дети, которые выходят каждый день на борьбу и гибнут в войнах по всему миру."," Современная политика пытается сохранить это понятие «мы» и «они» со стеной между ними."} end;
		if rnd==32 then msg={"Я понял, что надежда почти никогда не связана с разумом, она лишена здравого смысла,"," я считаю, что она рождается инстинктом."} end;
		if rnd==33 then msg={"Время отдает все и забирает все. Все меняется, но ничего не погибает."} end;
		if rnd==34 then msg={"Я не верю в смерть, потому что нет человека, который бы знал, что на самом деле это произошло."} end;
		if rnd==35 then msg={"Странно, что они боятся смерти. Жизнь причиняет гораздо больше боли, чем смерть."} end;
		if rnd==36 then msg={"Не позволяйте поведению других разрушить ваш внутренний мир."} end;
		if rnd==37 then msg={"Когда очевидно, что цели не могут быть достигнуты, не корректируйте цели, а корректируйте действия."} end;
		if rnd==38 then msg={"Живи так, как будто завтра умрешь. Учись так, как будто тебе суждено жить вечно."} end;
		if rnd==39 then msg={"Есть только один способ избежать критики: ничего не делать, ничего не говорить и быть ничем."} end;
		if rnd==40 then msg={"Чем больше человек размышляет о хороших мыслях, тем лучше будет его мир и мир в целом."} end;
		if rnd==41 then msg={"Чтобы знать, что думают люди, обращайте внимание на то, что они делают, а не на то, что они говорят."} end;
		if rnd==42 then msg={"Мы не описываем мир, который видим. Мы видим мир, который можем описать."} end;
		if rnd==43 then msg={"Философия написана в той великой книге, которая всегда лежит перед нашими глазами, - я имею в виду вселенную."} end;
		if rnd==44 then msg={"Человек, совершивший ошибку и не исправивший ее, совершает еще одну ошибку."} end;
		if rnd==45 then msg={"Если вы в депрессии, вы живете в прошлом. Если вы беспокоитесь, вы живете в будущем."," Если вы пребываете в покое, вы живете настоящим."} end;
		if rnd==46 then msg={"Лягушка в пруду мало знает об огромном океане."} end;
		if rnd==47 then msg={"Человек любит только считать свои проблемы. Он не считает свое счастье."} end;
		if rnd==48 then msg={"Мы те, кем притворяемся, поэтому мы должны быть осторожны с тем, кем притворяемся."} end;
		if rnd==49 then msg={"Когда вы любите кого-то, вы любите человека таким, какой он есть, а не таким, каким вы хотели бы его видеть."} end;
		if rnd==50 then msg={"Жизнь - это череда естественных и спонтанных изменений. Не сопротивляйтесь им, это только порождает печаль."," Пусть реальность будет реальностью."} end;
		if rnd==51 then msg={"На мой взгляд, мудрейший из всех - тот, кто хотя бы раз в месяц может называть себя дураком"," - способность, о которой сегодня не слышно."} end;
		if rnd==52 then msg={"Вы должны позволить происходящему случиться. Все должно быть в твоих глазах равным"," - добро и зло, красивое и уродливое, глупое и мудрое."} end;
		if rnd==53 then msg={"Когда возникает гнев, подумайте о последствиях."} end;
		if rnd==54 then msg={"Чем больше ты знаешь, тем больше знаешь, что не знаешь."} end;
		if rnd==55 then msg={"Если они плюют тебе в спину, значит, ты их опередил."} end;
		if rnd==56 then msg={"Разум существовал всегда, но не всегда в разумной форме."} end;
		if rnd==57 then msg={"Недостаточно иметь хороший ум, главное - правильно им пользоваться."} end;
		if rnd==58 then msg={"Неважно, насколько медленно ты идешь, пока ты не останавливаешься."} end;
		if rnd==59 then msg={"Чтобы осознать, кто ты есть, нужно отказаться от того, кем ты себя представляешь."} end;
		if rnd==60 then msg={"Есть только один путь - тот, которым идёшь ты."} end;
		if rnd==61 then msg={"Не спеши к смерти навстречу, она сама скоро придёт к тебе."} end;
		return msg;
	end;
	if SOULFUL_CONFIG["language"] =="EN" then 
		rnd=math.random(1,61);
		if rnd==1 then msg={"The most difficult thing is to get to know yourself. The easiest thing to do is to speak ill of others."} end;
		if rnd==2 then msg={"I can't teach you anything. I can only make you think."} end;
		if rnd==3 then msg={"The worst fight is the one that isn't fought."} end;
		if rnd==4 then msg={"Poverty does not come from a decrease in wealth, but from an increase in desires."} end;
		if rnd==5 then msg={"Don't hurt others with things that hurt you."} end;
		if rnd==6 then msg={"Expect a lot from yourself and not expect a lot from others. In this way, you will save yourself trouble."} end;
		if rnd==7 then msg={"Our deepest beliefs, the most unquestioned, are the most suspicious. They are our limit, our borders, our prison."} end;
		if rnd==8 then msg={"The heart has causes that the mind ignores."} end;
		if rnd==9 then msg={"Those who raise children well should be honored more than those who give birth to them. The first gives them life, the second the art of living well."} end;
		if rnd==10 then msg={"We rarely think about what we have, but always about what we lack."} end;
		if rnd==11 then msg={"I will never die for my beliefs because I can be wrong."} end;
		if rnd==12 then msg={"Our lives are always the result of our dominant thoughts."} end;
		if rnd==13 then msg={"It is often possible to learn more from a child's unexpected questions than from a man's speech."} end;
		if rnd==14 then msg={"Everyone sees who you are, but few understand who you are."} end;
		if rnd==15 then msg={"It's not what happens to you that matters, it's how you react."} end;
		if rnd==16 then msg={"The secret to happiness isn't always doing what you want, but always wanting what you do."} end;
		if rnd==17 then msg={"Patience is bitter, but its fruit is sweet."} end;
		if rnd==18 then msg={"Our envy always lasts longer than the happiness of the one we envy."} end;
		if rnd==19 then msg={"A life without philosophizing is, in fact, closing one's eyes without ever trying to open them."} end;
		if rnd==20 then msg={"The past has no power over the present moment."} end;
		if rnd==21 then msg={"Believe that your life is worth it, and that belief will help create that fact."} end;
		if rnd==22 then msg={"We don't see things as they are, but as we are."} end;
		if rnd==23 then msg={"The more people I know, the more I love my dog."} end;
		if rnd==24 then msg={"Think like a man of action, act like a man of thought."} end;
		if rnd==25 then msg={"The roots of the formation are bitter, but their fruits are sweet."} end;
		if rnd==26 then msg={"Life is very simple, but we insist on making it complicated."} end;
		if rnd==27 then msg={"Those who lead and pull the world are not machines, but ideas."} end;
		if rnd==28 then msg={"Those who believe that money does everything end up doing everything for money."} end;
		if rnd==29 then msg={"We are more sincere when we are angry than when we are calm."} end;
		if rnd==30 then msg={"Non-paradoxical thought is almost intolerable, thought is self-contained, coherent, which does not admit of paradox."} end;
		if rnd==31 then msg={"There are parents, brothers, children who go out every day to fight and die in wars around the world. Modern politics tries to preserve this notion of <us> and <them> with a wall between them."} end;
		if rnd==32 then msg={"I realized that hope is almost never connected with reason, it is devoid of common sense, I believe that it is born of instinct."} end;
		if rnd==33 then msg={"Time gives everything and takes everything away. Everything changes, but nothing dies."} end;
		if rnd==34 then msg={"I don't believe in death because there's no one who knows it actually happened."} end;
		if rnd==35 then msg={"It's strange that they're afraid of death. Life causes much more pain than death."} end;
		if rnd==36 then msg={"Don't let the behavior of others destroy your inner world."} end;
		if rnd==37 then msg={"When it is obvious that the goals cannot be achieved, do not adjust the goals, but adjust the actions."} end;
		if rnd==38 then msg={"Live like you're going to die tomorrow Learn as if you are destined to live forever."} end;
		if rnd==39 then msg={"There is only one way to avoid criticism: do nothing, say nothing, and be nothing."} end;
		if rnd==40 then msg={"The more a person thinks about good thoughts, the better his world and the world as a whole will be."} end;
		if rnd==41 then msg={"To know what people are thinking, pay attention to what they do, not what they say."} end;
		if rnd==42 then msg={"We don't describe the world we see. We see a world that we can describe."} end;
		if rnd==43 then msg={"Philosophy is written in that great book that is always before our eyes, and I mean the universe."} end;
		if rnd==44 then msg={"A person who makes a mistake and doesn't correct it makes another mistake."} end;
		if rnd==45 then msg={"If you're depressed, you're living in the past. If you're worried, you're living in the future. If you are at peace, you are living in the present."} end;
		if rnd==46 then msg={"The frog in the pond doesn't know much about the vast ocean."} end;
		if rnd==47 then msg={"A person only likes to count his problems. He doesn't count his happiness."} end;
		if rnd==48 then msg={"We are who we pretend to be, so we have to be careful who we pretend to be."} end;
		if rnd==49 then msg={"When you love someone, you love them for who they are, not as you would like them to be."} end;
		if rnd==50 then msg={"Life is a series of natural and spontaneous changes. Do not resist them, it only breeds sorrow. Let reality be reality."} end;
		if rnd==51 then msg={"In my opinion, the wisest of all is the one who can call himself a fool at least once a month, an ability that is unheard of today."} end;
		if rnd==52 then msg={"You have to let it happen. Everything should be equal in your eyes - good and evil, beautiful and ugly, stupid and wise."} end;
		if rnd==53 then msg={"When anger arises, think about the consequences."} end;
		if rnd==54 then msg={"The more you know, the more you know what you don't know."} end;
		if rnd==55 then msg={"If they spit in your back, then you're ahead of them."} end;
		if rnd==56 then msg={"Mind has always existed, but not always in a rational form."} end;
		if rnd==57 then msg={"It is not enough to have a good mind, the main thing is to use it correctly."} end;
		if rnd==58 then msg={"It doesn't matter how slow you go, as long as you don't stop."} end;
		if rnd==59 then msg={"In order to realize who you are, you need to give up who you think you are."} end;
		if rnd==60 then msg={"There is only one way, and that is the way you go."} end;
		if rnd==61 then msg={"Do not rush to meet death, it will soon come to you."} end;
		return msg;
	end;
end;